export const PETAL_CONSTANTS = {
	MIN_SIZE: 5,
	MAX_SIZE: 20,
	MIN_DELAY: 0,
	MAX_DELAY: 5,
	MIN_DURATION: 10,
	MAX_DURATION: 20,
	MIN_ROTATION: 180,
	MAX_ROTATION: 540,
	MIN_DRIFT_AMPLITUDE: 10,
	MAX_DRIFT_AMPLITUDE: 50,
}

// 花びらアニメーションの定数
export const PETAL_ANIMATION_CONSTANTS = {
	// 色関連
	MIN_HUE: 350,
	MAX_HUE: 360,
	MIN_SATURATION: 80,
	MAX_SATURATION: 100,
	MIN_LIGHTNESS: 80,
	MAX_LIGHTNESS: 90,

	// サイズ関連
	MIN_SIZE: 5,
	MAX_SIZE: 20,

	// アニメーション速度関連
	MIN_DELAY: 0,
	MAX_DELAY: 5,
	MIN_DURATION: 10,
	MAX_DURATION: 20,
	MIN_ROTATION: 180,
	MAX_ROTATION: 540,

	// ドリフト関連
	MIN_DRIFT_AMPLITUDE: 10,
	MAX_DRIFT_AMPLITUDE: 50,
	MIN_DRIFT_SPEED: 3,
	MAX_DRIFT_SPEED: 8,

	// 光効果関連
	MIN_SPARKLE_SIZE: 2,
	MAX_SPARKLE_SIZE: 5,
	MIN_SPARKLE_DURATION: 3,
	MAX_SPARKLE_DURATION: 8,
	MIN_SPARKLE_OPACITY: 0.3,
	MAX_SPARKLE_OPACITY: 0.7,
}
