export const PETAL_CONSTANTS = {
	MIN_SIZE: 5,
	MAX_SIZE: 20,
	MIN_DELAY: 0,
	MAX_DELAY: 5,
	MIN_DURATION: 10,
	MAX_DURATION: 20,
	MIN_ROTATION: 180,
	MAX_ROTATION: 540,
	MIN_DRIFT_AMPLITUDE: 10,
	MAX_DRIFT_AMPLITUDE: 50,
}
